# NumPy Öğrenirken Bir Takım Saçmalamalarım

# NumPy Dizileri

NumPy dizileri temelde iki şekilde gelir: **vektörler** ve **matrisler**. Vektörler, 1-boyutlu ve matrisler, 2-boyutlu dizilerdir.

## Neden sadece liste değilde, Numpy dizisini kullanmalıyım?
*Standart* python liste nesnesi yerine Numpy dizisi kullanmanın başlıca nedenleri şunlardır:
* Numpy dizisinin listeye karşın Bellek Verimliliği
* N-boyutlu nesnelere kolayca genişletilebilmesi
* Numpy dizisinin hesaplama hızı (yaklaşık 50 kat daha hızlı)
* Numpy ile yayın işlemleri (broadcasting) ve fonksiyonları
* Kullandığımız tüm veri bilimi ve makine öğrenmesi kütüphanelerinin Numpy ile oluşturulmuş olması.

### NumPy dizisinin ve Python listesinin Tipi:

In [3]:
import numpy as np

In [4]:
my_list = [1,2,3]
my_array = np.array(my_list)

In [5]:
type(my_list)

list

In [6]:
type(my_array)

numpy.ndarray

## Nesnelerden NumPy Dizileri Oluşturma

- **Python Listesinden** doğrudan dönüştürerek Numpy dizisi oluşturma:

In [7]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [8]:
np.array(my_list)

array([1, 2, 3])

In [9]:
type(np.array(my_list))

numpy.ndarray

In [10]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
type(my_matrix)

list

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
type(np.array(my_matrix))

numpy.ndarray

## Numpy dizisi oluşturmak için yerleşik yöntemler

Numpy'da dizi oluşturmanın birçok yerleşik yolu vardır.

- **arange :** Belirli bir aralıkta eşit aralıklı tamsayı değerleri içeren numpy dizisi döndüren Numpy fonksiyonu

In [13]:
# 0'dan 10(hariç)'a kadar bir numpy tam sayı dizisi oluşturma
np.arange(0,10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
 #step size girerek artımlı bir numpy tam sayı dizisi oluşturma. 0'dan 11(hariç)'e ikişer atlayarak
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

 **zeros ve ones :** $0$ veya $1$ floating dizileri oluşturma

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones(3)

array([1., 1., 1.])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

- **linspace :** Belirtilen aralıkta eşit aralıklı sayılar döndüren Numpy fonksiyonu

In [21]:
# 0 ile 10 (dahil) arasında 3 elemanlı eşit aralıklı numpy dizisi döndürme
np.linspace(0,10,3) 

array([ 0.,  5., 10.])

In [22]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [23]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

- **eye :** Birim matris oluşturan Numpy fonksiyonu 

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

- **Random :** Numpy'ın rasgele sayı dizisi oluşturan fonksiyonu:

> **rand :** Verilen şekle sahip bir dizi oluşturan ve onu ``[0, 1)`` yarı açık aralığında üniform dağılımlı rastgele örneklerle dolduran Numpy fonksiyonu 

In [25]:
np.random.rand(5)

array([0.54824294, 0.17793167, 0.93003968, 0.04759549, 0.97579767])

In [26]:
np.random.rand(5,5)

array([[0.8065897 , 0.20853672, 0.47673092, 0.11291748, 0.63371445],
       [0.59736372, 0.90498297, 0.0789809 , 0.36307975, 0.06896916],
       [0.10940091, 0.1490048 , 0.71447277, 0.76334345, 0.98536555],
       [0.39195451, 0.06930434, 0.05990441, 0.08373389, 0.56819481],
       [0.37844236, 0.17467638, 0.60067502, 0.5722431 , 0.49075158]])

> **randn :** 'Standart normal' ortalaması 0, varyansı 1 olan dağılımlı örnekler döndüren Numpy fonksiyonu. Üniform olan **rand**'ın aksine, sıfıra yakın değerlerin görünme olasılığı daha yüksektir

In [27]:
np.random.randn(2)

array([-1.01083627,  0.58291032])

In [28]:
np.random.randn(5,5)

array([[-1.14366998, -0.56346637,  0.22846954,  0.04928024,  1.0746789 ],
       [-2.57702212, -0.04322162,  1.11173578,  1.44536308,  1.5714513 ],
       [-1.73981013,  0.79409357, -0.08181791, -0.88731547, -0.07898011],
       [-1.44149233, -0.44101683,  0.45055748,  0.44074257,  0.39602084],
       [-2.02069739,  1.43484552, -1.87233266,  0.94252376, -0.18706704]])

> **randint :** 'low' (dahil) ile 'high' (hariç) arasında rastgele tamsayılar döndüren Numpy fonksiyonu

In [29]:
np.random.randint(1,100)

37

In [32]:
np.random.randint(1,10,10)

array([5, 1, 1, 9, 1, 3, 4, 5, 5, 5])

> *seed :* Aynı 'random' sonuçların yeniden üretilebilmesinde rastgele durumu ayarlamak için kullanılır

In [41]:
np.random.seed(42)
np.random.randint(4,20,3)

array([10,  7, 16])

In [42]:
np.random.seed(42)
np.random.randint(4,20,3)

array([10,  7, 16])

## Numpy Dizisinin Öznitelikleri ve Yöntemleri

In [94]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [95]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [96]:
ranarr

array([15, 44, 17, 46, 23, 25, 24, 44, 40, 28])

> **reshape-**
Aynı verileri içeren yeni şekilli bir dizi döndüren Numpy fonksiyonu

In [97]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

> **max, min, argmax, argmin-**
Maksimum veya minimum değerleri veya **argmin** veya **argmax** kullanarak indeks konumlarını bulmak için yararlı yöntemlerdir.

In [98]:
ranarr

array([15, 44, 17, 46, 23, 25, 24, 44, 40, 28])

In [99]:
ranarr.max()

46

In [100]:
ranarr.argmax() # maksimum değerin index değerini döndüren fonksiyon

3

In [101]:
ranarr.min()

15

In [102]:
ranarr.argmin() # minimum değerin index değerini döndüren fonksiyon

0

> **shape-**
Dizilerin sahip olduğu bir niteliktir (yöntem değil)

In [103]:
# 25 sayıdan oluşan bir boyutlu vektör olduğunu görürüz. 
arr.shape

(25,)

In [104]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [105]:
arr.reshape(1,25)
# İki parantez grubu var dikkat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [106]:
arr.reshape(1,25).shape

(1, 25)

In [107]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [108]:
arr.reshape(25,1).shape

(25, 1)

> **dtype-**
Dizinin veri türünü veren fonksiyon

In [109]:
arr.dtype

dtype('int64')

In [110]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')

# SON!