# NumPy: İndeksleme ve Seçim

In [1]:
import numpy as np

In [2]:
# Örnek dizi oluşturma
arr = np.arange(0,11)

In [3]:
# Diziyi gösterme
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Parantez İndeksleme ve Seçimi
Bir dizinin bir veya bazı elemanlarını seçmenin en basit yolu, python listesine çok benzer

In [4]:
# Bir indeksteki değeri alma
arr[8]

8

In [5]:
# Bir aralıktaki değerleri alma
arr[1:5]

array([1, 2, 3, 4])

In [6]:
# Bir aralıktaki değerleri alma
arr[:5]

array([0, 1, 2, 3, 4])

## Yayınlama (Broadcasting)

NumPy dizileri, yayınlama yetenekleri nedeniyle normal Python listelerinden farklıdır. Listelerle, aynı boyut ve şekle sahip yeni bir listeye yeniden atayabilirsiniz. Yani, bir listedeki ilk 5 elemanı yeni bir değerle değiştirmek isterseniz, yeni bir 5 elemanlı listeye geçmeniz gerekir. NumPy dizileriyle, büyük bir indeks aralığında tek bir değer yayınlayabilirsiniz

In [7]:
# İndeks aralığı ile değer ayarlama (Yayınlama-Broadcasting)
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
# Diziyi sıfırla, birazdan neden sıfırlamak zorunda kaldığımızı anlayacağız
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# Dilimler hakkında önemli notlar
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [10]:
# Dilimi değiştirme
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [11]:
arr #Değişiklikler orjinal dizide de değişiyor.

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Veriler kopyalanmaz, orijinal dizinin bir görünümüdür! Bu, hafıza problemlerini önler!

In [12]:
# Bir kopya almak için açıkca ayarlamalısınız
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## 2D bir diziyi (matrisi) indeksleme

Genel format: **arr_2d[row][col]** veya **arr_2d[row,col]**. Netlik için virgül gösterimini kullanmanızı öneririm.

In [13]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
# Satır dizisi oluşturma
arr_2d[1]

array([20, 25, 30])

In [18]:
# Format: arr_2d[row][col] veya arr_2d[row,col]

# Bir elemanın değerini alma: 1.yol
arr_2d[1][0]

20

In [19]:
# Bir elemanın değerini alma: 2.yol
arr_2d[1,0]

20

In [20]:
# 2D diziyi dilimleme

# Sağ üst köşeden (2,2) şekilli dizi dilimleme
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [21]:
# Alt satır şekilli dizi dilimleme
arr_2d[2]

array([35, 40, 45])

In [22]:
# Alt satır şekilli dizi dilimleme
arr_2d[2,:]

array([35, 40, 45])

## Daha Fazla İndeksleme
2B matrisi indekslemek, özellikle adım boyutunda eklemeye başladığınızda, ilk başta biraz kafa karıştırıcı olabilir. Bunun gibi faydalı görseller bulmak için google görsel aramada *NumPy indekslemeyi* deneyin:

<img src= 'image/numpy_indexing.png' width=500/>

## Koşullu Seçim

Daha sonra doğrudan pandas'a çevrilecek çok temel bir kavramdır, bu kısmı anladığınızdan emin olun!

Karşılaştırma operatörlerine dayalı seçim için parantezlerin nasıl kullanılacağını kısaca gözden geçirelim.

In [23]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [25]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [26]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [27]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [28]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# SON!